version: '2'
services:
  c1:
    container_name: c1_wakuta
    image: cassandra:3.11 
    ports:
          - '7000:7000'
          - '7001:7001'
          - '7199:7199'
          - '9042:9042'
          - '9160:9160'
    tty: true
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=badr
      - CASSANDRA_SEEDS=sadr
