version: '2'
services:
  c1:
    container_name: c1_wakuta
    image: cassandra:3.11 
    ports:
          - '7000:7000'
          - '7001:7001'
          - '7199:7199'
          - '9042:9042'
          - '9160:9160'
    tty: true
    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
      - CASSANDRA_SEEDS=127.0.0.1
